// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABtQqDk6leDr4qY9N6i_BVPCdJ0Om-SOE',
    appId: '1:969137227598:web:806a591569db121c19801f',
    messagingSenderId: '969137227598',
    projectId: 'chat-app-31dae',
    authDomain: 'chat-app-31dae.firebaseapp.com',
    storageBucket: 'chat-app-31dae.appspot.com',
    measurementId: 'G-M4BCSC8FJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmSRf1cuB5PxnlTV1xW2iDMSRp4Q5C0CE',
    appId: '1:969137227598:android:10dec83d23d29bb419801f',
    messagingSenderId: '969137227598',
    projectId: 'chat-app-31dae',
    storageBucket: 'chat-app-31dae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZpLK1MNxl4J2xcc2NLjwa87eeQHs5xZI',
    appId: '1:969137227598:ios:2b269b4189c7e11b19801f',
    messagingSenderId: '969137227598',
    projectId: 'chat-app-31dae',
    storageBucket: 'chat-app-31dae.appspot.com',
    iosClientId: '969137227598-crdkamn20dq7itfdl3ht2cibebg083uk.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZpLK1MNxl4J2xcc2NLjwa87eeQHs5xZI',
    appId: '1:969137227598:ios:aeff0f6e2371e6be19801f',
    messagingSenderId: '969137227598',
    projectId: 'chat-app-31dae',
    storageBucket: 'chat-app-31dae.appspot.com',
    iosClientId: '969137227598-jggasq205o4r32c19dlrlg1q12h06e8b.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
